result: ExceptionThrown
thrown: throwable:ArithmeticException

