result: int:6
thrown: NoExceptionThrown

